#!/usr/bin/env bash
#
# mk-init.sh - initialize the SDK .config from chip/board defconfigs.
#
# Usage:
#   ./mk-init.sh                  # only creates .config when it is missing
#   ./mk-init.sh <chip> <config>  # non-interactive selection
#   ./mk-init.sh --force          # re-run selection even if .config exists
#
# Running this script as "mk-chip" forces re-selection; otherwise use --force.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
RK_SDK_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"

RK_CONFIG="$RK_SDK_DIR/.config"
RK_CHIP_DIR="$RK_SDK_DIR/device/chip"

# If this script is reached through the mk-chip symlink, force re-selection.
CMD_NAME="$(basename -- "${0:-mk-init.sh}")"
FORCE=0
[ "$CMD_NAME" = "mk-chip" ] && FORCE=1

usage()
{
	cat <<EOF
Usage: $(basename -- "${0:-mk-init.sh}") [--force] [<chip> [<board-defconfig>]]

Creates $RK_SDK_DIR/.config when it does not exist yet.
The config is generated by merging <chip>_defconfig and the selected
board *_defconfig from $RK_CHIP_DIR/<chip>.

Options:
  -f, --force   Regenerate .config even if it already exists.
  -h, --help    Show this help.
EOF
}

die()
{
	echo "error: $*" >&2
	exit 1
}

purple()
{
	printf '\033[35m%s\033[0m\n' "$*"
}

pick_menu()
{
	local -n menu_items="$1"
	local menu_title="$2"
	local menu_result="$3"
	local answer i

	echo
	purple "$menu_title"
	echo
	for i in "${!menu_items[@]}"; do
		printf '%d. %s\n' "$((i + 1))" "${menu_items[$i]}"
	done

	while :; do
		if ! IFS= read -r -p "Which would you like? [1]: " answer; then
			echo >&2
			die "no selection made"
		fi
		answer="${answer:-1}"
		if [[ "$answer" =~ ^[0-9]+$ ]] &&
			(( answer >= 1 && answer <= ${#menu_items[@]} )); then
			printf -v "$menu_result" '%s' "${menu_items[$((answer - 1))]}"
			return 0
		fi
		echo "Invalid selection: $answer (choose 1-${#menu_items[@]})" >&2
	done
}

CHIP_ARG=""
BOARD_ARG=""
while [ $# -gt 0 ]; do
	case "$1" in
		-f|--force)
			FORCE=1
			;;
		-h|--help)
			usage
			exit 0
			;;
		-*)
			die "unknown option: $1"
			;;
		*)
			if [ -z "$CHIP_ARG" ]; then
				CHIP_ARG="$1"
			elif [ -z "$BOARD_ARG" ]; then
				BOARD_ARG="$1"
			else
				die "too many arguments: $1"
			fi
			;;
	esac
	shift
done

if [ "$FORCE" -eq 0 ] && [ -f "$RK_CONFIG" ] && [ -s "$RK_CONFIG" ]; then
	purple "SDK config already exists: $RK_CONFIG"
	purple "Run ./build.sh init to select a different config."
	exit 0
fi

[ -d "$RK_CHIP_DIR" ] || die "chip directory not found: $RK_CHIP_DIR"

# --- Select chip -----------------------------------------------------------
chips=()
while IFS= read -r chip_dir; do
	chips+=("$chip_dir")
done < <(find "$RK_CHIP_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)

[ "${#chips[@]}" -gt 0 ] || die "no chip directories found under $RK_CHIP_DIR"

if [ -n "$CHIP_ARG" ]; then
	chip="$CHIP_ARG"
	[ -d "$RK_CHIP_DIR/$chip" ] || die "unknown chip: $chip"
elif [ "${#chips[@]}" -eq 1 ]; then
	chip="${chips[0]}"
	purple "Only one chip available, using: $chip"
else
	pick_menu chips "Pick a chip:" chip
fi

purple "Switching to chip: $chip"

CHIP_DIR="$RK_CHIP_DIR/$chip"
CHIP_DEFCONFIG="$CHIP_DIR/${chip}_defconfig"
[ -f "$CHIP_DEFCONFIG" ] || CHIP_DEFCONFIG="$CHIP_DIR/rockchip_defconfig"

# --- Select board config ---------------------------------------------------
board_configs=()
if [ -f "$CHIP_DIR/rockchip_defconfig" ]; then
	board_configs+=("rockchip_defconfig")
fi
if [ -f "$CHIP_DIR/${chip}_defconfig" ]; then
	board_configs+=("${chip}_defconfig")
fi
for defconfig in "$CHIP_DIR"/*_defconfig; do
	[ -f "$defconfig" ] || continue
	defconfig_name="$(basename -- "$defconfig")"
	case "$defconfig_name" in
		rockchip_defconfig|"${chip}_defconfig")
			continue
			;;
	esac
	board_configs+=("$defconfig_name")
done

[ "${#board_configs[@]}" -gt 0 ] || die "no *_defconfig found in $CHIP_DIR"

if [ -n "$BOARD_ARG" ]; then
	board_config="$BOARD_ARG"
	case "$board_config" in
		/*)
			board_config="$board_config"
			;;
		*/*)
			board_config="$RK_SDK_DIR/$board_config"
			;;
		*)
			board_config="$CHIP_DIR/$board_config"
			;;
	esac
	[ -f "$board_config" ] || die "board config not found: $board_config"
	board_name="$(basename -- "$board_config")"
else
	if [ "${#board_configs[@]}" -eq 1 ]; then
		board_name="${board_configs[0]}"
		purple "Only one board config available, using: $board_name"
	else
		pick_menu board_configs "Pick a defconfig:" board_name
	fi
fi

BOARD_DEFCONFIG="$CHIP_DIR/$board_name"
[ -f "$BOARD_DEFCONFIG" ] || die "board config not found: $BOARD_DEFCONFIG"
purple "Switching to defconfig: $board_name"

UBOOT_CFG_DEBUG="$(sed -n 's/^[[:space:]]*RK_UBOOT_CFG=//p' "$BOARD_DEFCONFIG" | tail -n 1)"
UBOOT_CFG_DEBUG="${UBOOT_CFG_DEBUG%\"}"
UBOOT_CFG_DEBUG="${UBOOT_CFG_DEBUG#\"}"

# --- Merge and write .config ----------------------------------------------
TMP_CONFIG="$(mktemp "$RK_CONFIG.XXXXXX")"
{
	echo "# RockChip SDK configuration"
	echo "# Generated by $CMD_NAME at $(date '+%Y-%m-%d %H:%M:%S')"
	echo "# Chip: $chip"
	echo "# Board config: $board_name"
	echo "# U-boot defconfig: ${UBOOT_CFG_DEBUG:-<not set>}"
	echo

	if [ "$CHIP_DEFCONFIG" != "$BOARD_DEFCONFIG" ] && [ -f "$CHIP_DEFCONFIG" ]; then
		echo "# --- $(basename -- "$CHIP_DEFCONFIG") ---"
		cat "$CHIP_DEFCONFIG"
		echo
	fi

	echo "# --- $board_name ---"
	cat "$BOARD_DEFCONFIG"
	echo

	# Keep the active selection explicit, no matter what the fragments contain.
	echo "RK_CHIP=\"$chip\""
	echo "RK_CONFIG=\"$board_name\""
} > "$TMP_CONFIG"

mv "$TMP_CONFIG" "$RK_CONFIG"

# Match the requested kernel version to a kernel-<version> source directory.
RK_CONFIG_PATH="$RK_CONFIG"
# shellcheck disable=SC1090
. "$RK_CONFIG"
KERNEL_VERSION="${RK_KERNEL_VERSION:-}"
[ -n "$KERNEL_VERSION" ] || die "RK_KERNEL_VERSION is not set in generated config"

KERNEL_SRC="$RK_SDK_DIR/kernel-$KERNEL_VERSION"
KERNEL_LINK="$RK_SDK_DIR/kernel"
[ -d "$KERNEL_SRC" ] || die "kernel directory not found: $KERNEL_SRC"
if [ -e "$KERNEL_LINK" ] && [ ! -L "$KERNEL_LINK" ]; then
	die "kernel path exists and is not a symlink: $KERNEL_LINK"
fi
ln -sfn "kernel-$KERNEL_VERSION" "$KERNEL_LINK"

purple "SDK config generated: $RK_CONFIG_PATH"
purple "  chip:         $chip"
purple "  board config: $board_name"
purple "  u-boot cfg:   ${RK_UBOOT_CFG:-<not set>}"
purple "  rockchip tpl: ${ROCKCHIP_TPL:-<not set>}"
purple "  bl31:         ${BL31:-<not set>}"
purple "  kernel link:  $KERNEL_LINK -> kernel-$KERNEL_VERSION"
