#!/bin/bash
#
# Minimal kernel + extboot builder.
# Reads SDK-level settings from $RK_SDK_DIR/.config when available.

set -e

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
RK_SDK_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
RK_CONFIG="$RK_SDK_DIR/.config"

KERNEL_DIR="$RK_SDK_DIR/kernel"

die()
{
	echo "error: $*" >&2
	exit 1
}

purple()
{
	printf '\033[35m%s\033[0m\n' "$*"
}

# Read the SDK-level config generated by mk-init.sh.
if [ -f "$RK_CONFIG" ] && [ -s "$RK_CONFIG" ]; then
	# shellcheck disable=SC1090
	. "$RK_CONFIG"
fi

# --- Build settings (SDK config overrides, defaults below) ---
DTS_NAME="${RK_KERNEL_DTS_NAME:-rk3588-orangepi-5-plus}"
KERNEL_CFG="${RK_KERNEL_CFG:-}"
ARCH="arm64"
CROSS_COMPILE="aarch64-linux-gnu-"
RK_OUTPUT_DIR="$RK_SDK_DIR/output"
BOOT_DIR="$RK_OUTPUT_DIR/extboot"
BOOT_IMG="$RK_OUTPUT_DIR/extboot.img"
ROOTFS_STAGING="$RK_OUTPUT_DIR/rootfs"

DTB="$KERNEL_DIR/arch/$ARCH/boot/dts/rockchip/$DTS_NAME.dtb"
IMAGE="$KERNEL_DIR/arch/$ARCH/boot/Image"
UENV_DIR="$KERNEL_DIR/arch/$ARCH/boot/dts/rockchip/uEnv"
KERNEL_JOBS="$(nproc)"
KERNEL_DEFCONFIG=""
if [ -n "$KERNEL_CFG" ]; then
	KERNEL_DEFCONFIG="$KERNEL_DIR/arch/$ARCH/configs/$KERNEL_CFG"
fi

kbuild()
{
	make -C "$KERNEL_DIR" ARCH="$ARCH" CROSS_COMPILE="$CROSS_COMPILE" "$@"
}

show_build_params()
{
	purple "==> Kernel build parameters"
	purple "    KERNEL_DIR      = $KERNEL_DIR"
	purple "    ARCH            = $ARCH"
	purple "    CROSS_COMPILE   = $CROSS_COMPILE"
	purple "    DEFCONFIG       = ${KERNEL_CFG:-<none>}"
	purple "    DEFCONFIG_FILE  = ${KERNEL_DEFCONFIG:-<none>}"
	purple "    DTS_NAME        = $DTS_NAME"
	purple "    JOBS            = $KERNEL_JOBS"
	purple "    TARGETS         = Image dtbs modules"
}

build_kernel()
{
	# Check the requested defconfig before printing build parameters.
	[ -n "$KERNEL_CFG" ] || die "RK_KERNEL_CFG is empty; cannot determine kernel defconfig"
	[ -n "$KERNEL_DEFCONFIG" ] || die "kernel defconfig path is empty"
	[ -f "$KERNEL_DEFCONFIG" ] || die "kernel defconfig not found: $KERNEL_DEFCONFIG"

	show_build_params

	purple "==> Applying kernel defconfig: $KERNEL_CFG"
	kbuild "$KERNEL_CFG"

	purple "==> Building kernel, dtbs and modules"
	kbuild Image dtbs modules -j"$KERNEL_JOBS"
}

pack_extboot()
{
	purple "==> Packing extboot partition"

	rm -rf "$BOOT_DIR"
	mkdir -p "$BOOT_DIR/dtb/rockchip" "$BOOT_DIR/uEnv"

	[ -f "$IMAGE" ] || { echo "error: $IMAGE not found" >&2; exit 1; }
	[ -f "$DTB" ] || { echo "error: $DTB not found" >&2; exit 1; }

	KERNEL_VER="$(cat "$KERNEL_DIR/include/config/kernel.release" 2>/dev/null || true)"
	[ -n "$KERNEL_VER" ] || KERNEL_VER="unknown"

	cp -a "$IMAGE" "$BOOT_DIR/Image-$KERNEL_VER"
	cp -a "$DTB" "$BOOT_DIR/rk-kernel.dtb"
	cp -a "$DTB" "$BOOT_DIR/dtb/rockchip/"

	# uEnv.txt is consumed by boot.scr (uEnv import / overlay handling).
	if [ -f "$UENV_DIR/uEnv.txt" ]; then
		cp -a "$UENV_DIR/uEnv.txt" "$BOOT_DIR/uEnv/"
		sed -i "s/^uname_r=.*/uname_r=${KERNEL_VER}/" "$BOOT_DIR/uEnv/uEnv.txt"
	else
		echo "warning: $UENV_DIR/uEnv.txt not found, skipping" >&2
	fi

	# boot.cmd -> boot.scr (primary boot path, runs before extlinux).
	if [ -f "$UENV_DIR/boot.cmd" ]; then
		cp -a "$UENV_DIR/boot.cmd" "$BOOT_DIR/boot.cmd"
		if command -v mkimage >/dev/null 2>&1; then
			mkimage -T script -C none -d "$BOOT_DIR/boot.cmd" "$BOOT_DIR/boot.scr" >/dev/null
		else
			echo "warning: mkimage not found, boot.scr not generated" >&2
		fi
	else
		echo "warning: $UENV_DIR/boot.cmd not found, skipping boot.scr" >&2
	fi

	# Install modules into a staging rootfs tree.
	rm -rf "$ROOTFS_STAGING"
	mkdir -p "$ROOTFS_STAGING"
	kbuild INSTALL_MOD_PATH="$ROOTFS_STAGING" modules_install

	# Create the ext2 boot partition image.
	rm -f "$BOOT_IMG"
	truncate -s 128M "$BOOT_IMG"
	mkfs.ext2 -F -L boot -d "$BOOT_DIR" "$BOOT_IMG"

	purple "  Image: $BOOT_IMG is ready"
	purple "  Boot files: $BOOT_DIR"
	purple "  Modules: $ROOTFS_STAGING"
}

build_kernel
pack_extboot
